# Generated by Django 2.0 on 2020-05-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daignostic_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antibodies',
            options={'verbose_name': 'AntiBody', 'verbose_name_plural': 'AntiBodies'},
        ),
    ]
