# Generated by Django 2.0 on 2020-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daignostic_tests', '0002_auto_20200510_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='panels',
            field=models.ManyToManyField(to='daignostic_tests.Panel'),
        ),
    ]
