# Generated by Django 2.0 on 2020-05-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daignostic_tests', '0003_patient_panels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='panels',
            field=models.ManyToManyField(blank=True, null=True, to='daignostic_tests.Panel'),
        ),
    ]
